# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
        migrations.AddField(
            model_name='courses',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u9700\u77e5'),
        ),
    ]
